      - name: Commit Updated CSV Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          touch open_positions.csv closed_positions.csv
          git add open_positions.csv closed_positions.csv
          git diff --staged --quiet || git commit -m "Update open and closed positions [skip ci]"
          git push
